### ISSUE TITLE
InputHasContent.java:43-47: All the matchers should...

### ISSUE THREAD

**Issue by 0pdd** [llorllale/cactoos-matchers#20]
The puzzle `7-0cc4122b` from #7 has to be resolved:

https://github.com/llorllale/cactoos-matchers/blob/d3cd1e573af86241197711042a66a2162b4fccd0/src/main/java/org/llorllale/cactoos/matchers/InputHasContent.java#L43-L47

The puzzle was created by Victor Noël on 19-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/20#issuecomment-398513405))

@llorllale Job [#20](https://github.com/llorllale/cactoos-matchers/issues/20) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@dgroup I'm confused myself: this may not really apply.

@victornoel can you help?

**Comment by victornoel** [comment]
@dgroup @llorllale there are two things in the todo:
1. Some matchers in cactoos-matchers makes the method `matchesSafely` public, and when testing the matcher, those methods are tested. This is incorrect: to test the matcher and ensure they work properly, they must be tested directly as an argument of `assertThat` as in [ScalarHasValueTest#L54](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/ScalarHasValueTest.java#L54).
The test for [EndsWithTest](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/EndsWithTest.java) is not correct because it tests the method `matchesSafely` directly instead of testing the real behaviour of the matcher (the one normally invoked by `assertThat` and that is partially implemented by the superclasses `TypeSafeMatcher` and `BaseMatcher`) (btw, this is why inheritance is hell to test sometimes ;).
2. The matchers should report failure to match properly. Implementing `describeMismatchSafely` is the mean to do that when subclassing `TypeSafeMatcher`. You can see how this can then be tested correctly in [ScalarHasValueTest#L87](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/ScalarHasValueTest.java#L87). I am not clear what `TypeSafeDiagnosingMatcher` is for, but if it allows for matcher to properly describe the mismatch, then I think it's ok to use it.

**Comment by llorllale** [comment]
@victornoel got it

**Comment by dgroup** [comment]
@victornoel, please correct me if i'm wrong, the test from EndsWith shoud be like
```java
 /**
     * Give the negative testing result for the invalid arguments.
     */
    @Test
    public void matchNegative() {
        new Assertion<>(
            "The matcher gives negative result for the invalid arguments",
            () -> new EndsWith("!"),
            new IsNot<>(new Matches<>(new TextOf("The sentence.")))
        ).affirm();
    }

   /**
     * Matcher prints the actual value(s) properly in case of errors.
     * The actual/expected section are using only when testing is failed and
     *  we need to explain what exactly went wrong.
     */
    @Test
    public void describeActualValues() {
        new Assertion<>(
            "The matcher print the value which came for testing",
            () -> {
                final Description desc = new StringDescription();
                new EndsWith("").describeMismatch(new TextOf("ABC"), desc);
                return desc.toString();
            },
            new IsEqual<>("Text ending with \"ABC\"")
        ).affirm();
    }
``` 
If we are on the same page, I can start the implementation.

**Comment by victornoel** [comment]
@dgroup we are not on the same page, sorry :)

Write [this](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/ScalarHasValueTest.java#L54) but replace `ScalarHasValue` with `EndsWith`:
```
MatcherAssert.assertThat(
            "doesn't match end of String",
            new TextOf("The sentence!"),
            new EndsWith("!")
);
```

And the test the negative.

**Comment by victornoel** [comment]
@dgroup and then test that the errors are correct, like [this](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/ScalarHasValueTest.java#L74) and [this](https://github.com/llorllale/cactoos-matchers/blob/master/src/test/java/org/llorllale/cactoos/matchers/ScalarHasValueTest.java#L87)

**Comment by dgroup** [comment]
@victornoel, I understood.
The key point here is using of `@Rule` + `.expectMessage(` instead of calling the `matchesSafely` directly.
@llorllale, I think we need to fix the tests for all matchers in such way (with separate tasks of course). WDYT?

P.S: We are not using `MatcherAssert.assertThat` anymore (#52).

**Comment by victornoel** [comment]
@dgroup in that case, it should look like this:
```
new Assertion<>(
    "doesn't match end of String",
    () -> new TextOf("The sentence!"),
    new EndsWith("!")
);
```

Not the opposite. Also I suppose it would be good to introduce a secondary constructor for `Assertion` that takes a `T` and wraps it into a `Scalar<T>`. It would be easier to read…

**Comment by dgroup** [comment]
I also thought about secondary constructor

**Comment by llorllale** [comment]
@dgroup 

> @llorllale, I think we need to fix the tests for all matchers in such way (with separate tasks of course). WDYT?

Sure.

**Comment by dgroup** [comment]
@llorllale I'm ok to implement this task.
Please assign to me.

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/llorllale/cactoos-matchers/issues/20#issuecomment-449032520))

@llorllale The job [#20](https://github.com/llorllale/cactoos-matchers/issues/20) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/ba03a095-822c-4856-ab63-e429a1ef8842); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@0crat wait, as the #64 has quite huge changes, thus it will be double work without that request.

**Comment by 0crat** [comment]
> @0crat wait, as the #64 has quite huge changes, thus it will be double work without that request. ([here](https://github.com/llorllale/cactoos-matchers/issues/20#issuecomment-449786087))

@dgroup Can't understand "wait,", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0pdd** [comment]
The puzzle `7-0cc4122b` has disappeared from the source code, that's why I closed this issue.

**Comment by victornoel** [comment]
@llorllale I don't understand why removing the puzzle for this issue was accepted: this is not solved at all and the fix goes against what the puzzle was about

**Comment by 0crat** [comment]
The job [#20](https://github.com/llorllale/cactoos-matchers/issues/20) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by llorllale** [comment]
@victornoel we messed up, sorry

**Comment by 0pdd** [comment]
@0pdd the puzzle [#230](https://github.com/llorllale/cactoos-matchers/issues/230) is still not solved.
